[project]
id = "std"
name = "Mach Standard Library"
description = "Mach standard library"
version = "0.17.0"
src = "src"
out = "out/{target.name}/{profile.name}"

[target.linux-x86_64]
isa = "x86_64"
os  = "linux"
abi = "sysv64"

[target.linux-arm64]
isa = "aarch64"
os  = "linux"
abi = "aapcs64"

[profile.debug]
opt = 0

[profile.release]
opt = 2

[artifact.std]
kind = "static"
entry = "lib.mach"
out = "lib/std"
targets = ["*"]
link = ["kernel32", "ws2_32", "advapi32", "synch"]

[link.kernel32]
source = "system"
name = "kernel32.dll"
os = ["windows"]
export = true

[link.ws2_32]
source = "system"
name = "ws2_32.dll"
os = ["windows"]
export = true

[link.advapi32]
source = "system"
name = "advapi32.dll"
os = ["windows"]
export = true

[link.synch]
source = "system"
name = "api-ms-win-core-synch-l1-2-0.dll"
os = ["windows"]
export = true
