#!/usr/bin/env python3
# writes an entry that reaches every std module holding a test, each under its own os gate
#
# usage: entry.py <src root> <entry out> <modules out>
# the entry stands in for the whole-source load mach 5.12 dropped (mach#3813), so
# listing it gives every test a target can collect. a module whose os gate is not
# a form `refusals` reads is used unguarded, and then fails loudly on the targets
# it refuses rather than dropping out.
import re
import sys
from pathlib import Path

TEST = re.compile(r'^\s*test\s+[A-Za-z_][A-Za-z0-9_]*\s*\{', re.M)
OS_ONLY = re.compile(r'^(\s*(\$mach\.build\.os|\$mach\.os\.[a-z]+|==|!=|&&|\|\|)\s*)+$')


def refusals(text: str) -> list:
    # the os conditions under which a module refuses itself with `$error`. a chain
    # `$if (a) { .. } $or (b) { .. } $or { $error(..) }` refuses when no branch
    # holds, and `$if (a) { $error(..) }` refuses when a holds
    lines = text.split('\n')
    found = []
    i = 0
    while i < len(lines):
        head = re.match(r'^\$if \((.*)\) \{$', lines[i])
        if not head:
            i += 1
            continue
        branches = [head.group(1)]
        errs = []
        j = i
        while True:
            body = j + 1
            close = body
            while close < len(lines) and lines[close] != '}':
                close += 1
            errs.append(body < len(lines) and lines[body].lstrip().startswith('$error('))
            if close + 1 >= len(lines):
                break
            nxt = re.match(r'^\$or(?: \((.*)\))? \{$', lines[close + 1])
            if not nxt:
                break
            branches.append(nxt.group(1))
            j = close + 1
        i = j + 1
        conds = [c for c in branches if c is not None]
        if not all(OS_ONLY.match(c) for c in conds):
            continue
        if len(branches) == 1 and errs[0]:
            found.append('(%s)' % branches[0])
        elif branches[-1] is None and errs[-1] and not any(errs[:-1]):
            found.append('(%s)' % ' && '.join('!(%s)' % c for c in conds))
    return found


def main() -> int:
    src, entry, listing = Path(sys.argv[1]), Path(sys.argv[2]), Path(sys.argv[3])
    lines = ['# generated by test/selections/entry.py, every module that holds a test', '',
             'use std.runtime;', '']
    modules = []
    for path in sorted(src.rglob('*.mach')):
        rel = path.relative_to(src)
        if rel.parts[0] == 'lib':
            continue
        text = path.read_text()
        if not TEST.search(text):
            continue
        module = 'std.' + '.'.join(rel.with_suffix('').parts)
        alias = 'm%d' % len(modules)
        modules.append(str(Path('src') / rel))
        gates = refusals(text)
        if gates:
            lines.append('$if (%s) {' % ' || '.join(gates))
            lines.append('}')
            lines.append('$or {')
            lines.append('    use %s: %s;' % (alias, module))
            lines.append('}')
        else:
            lines.append('use %s: %s;' % (alias, module))
    entry.write_text('\n'.join(lines) + '\n')
    listing.write_text('\n'.join(modules) + '\n')
    return 0


if __name__ == '__main__':
    sys.exit(main())
